#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod config_ui;
mod dialogs;
mod framebuffer;
mod handle;
mod input;
mod safe_stop;
mod scsi_menu;
mod settings;
mod single_instance;

use config_ui::{cfg_to_toml, show_tab, JitEnv, Tab};
use dialogs::create_disk::CreateDiskDialog;
use dialogs::new_machine::{distribute_ram, NewMachineDialog};
use eframe::egui;
use egui::{Color32, RichText, ViewportCommand};
use handle::{Cmd, EmulatorHandle, Evt};
use iris::config::MachineConfig;
use safe_stop::{evaluate, reason_lines};
use settings::{GuiSettings, UI_SCALE_MAX, UI_SCALE_MIN};
use std::path::PathBuf;

/// Decode the bundled window/taskbar icon (256×256 RGBA PNG, generated by
/// `scripts/generate-icon.sh` from `iris-gui/assets/icon-original.png`).
/// Decoded with the `png` crate that iris-gui already depends on, so no extra
/// image dependency is pulled in.
fn load_icon() -> egui::IconData {
    const ICON_PNG: &[u8] = include_bytes!("../assets/icons/icon-256.png");
    let decoder = png::Decoder::new(std::io::Cursor::new(ICON_PNG));
    let mut reader = decoder.read_info().expect("decode icon PNG header");
    let mut rgba = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut rgba).expect("decode icon PNG pixels");
    rgba.truncate(info.buffer_size());
    egui::IconData {
        rgba,
        width: info.width,
        height: info.height,
    }
}

fn main() -> eframe::Result<()> {
    env_logger::init();
    // Prevent the iris lib from calling process::exit on guest soft-power-off
    // or CI `quit`. iris-gui never wants the embedder to die from a guest event.
    // Set this once, before any worker thread can read it.
    std::env::set_var("IRIS_NO_EXIT_ON_POWEROFF", "1");
    // Terminate a still-alive previous instance (a crash/hang or forgotten
    // copy that would otherwise keep the monitor/serial ports bound) and claim
    // the single-instance lock for ourselves.
    single_instance::acquire();
    let prefs = GuiSettings::load();
    let mut viewport = egui::ViewportBuilder::default()
        .with_title("iris — SGI Indy emulator")
        // app_id sets the X11 WM_CLASS / Wayland app_id so the compositor can
        // match an installed .desktop/icon (icons regenerated by
        // scripts/generate-icon.sh from iris-gui/assets/icon-original.png).
        .with_app_id("iris-gui")
        .with_icon(load_icon())
        .with_inner_size(prefs.window_size.unwrap_or([1100.0, 720.0]));
    if prefs.fullscreen {
        viewport = viewport.with_fullscreen(true);
    }
    let opts = eframe::NativeOptions {
        viewport,
        ..Default::default()
    };
    eframe::run_native(
        "iris-gui",
        opts,
        Box::new(|cc| {
            cc.egui_ctx.set_zoom_factor(prefs.ui_scale.clamp(UI_SCALE_MIN, UI_SCALE_MAX));
            Ok(Box::new(App::new(prefs)))
        }),
    )
}

struct App {
    prefs: GuiSettings,
    cfg: MachineConfig,
    /// Path to an iris.toml that was *imported* (for re-export). None for
    /// machines that originated from the GUI.
    cfg_path: Option<PathBuf>,
    /// Marks the current cfg as having unsaved (in-memory) changes.
    cfg_dirty: bool,
    /// Timestamp of the most recent edit; used to debounce auto-save.
    cfg_dirty_since: Option<std::time::Instant>,
    jit: JitEnv,
    tab: Tab,
    emu: EmulatorHandle,
    toast: Option<(String, std::time::Instant)>,
    fullscreen: bool,
    stop_modal: Option<StopModal>,
    missing_modal: Option<MissingDiskModal>,
    new_machine: NewMachineDialog,
    create_disk: CreateDiskDialog,
    /// If true, central panel shows the tabbed config editor; otherwise the
    /// welcome/status summary panel (default — most config lives in menus).
    show_config_editor: bool,
    save_state_name: String,
    restore_state_name: String,
    /// egui texture holding the most recent REX3 framebuffer. Allocated
    /// lazily on the first frame that needs it.
    fb_tex: Option<egui::TextureHandle>,
    /// Sequence number of the last frame we uploaded; used to skip the
    /// upload when the renderer hasn't produced a new frame.
    last_fb_seq: u64,
    /// Per-frame state for the egui→PS2 input pump (modifier diff,
    /// mouse button mask, last cursor position).
    input_state: input::InputState,
}

struct StopModal {
    lines: Vec<String>,
}

/// One SCSI device that is missing its backing file at Start time.
struct MissingDisk {
    id: u8,
    path: String,
    cdrom: bool,
}

/// Modal shown when one or more SCSI image files are missing on Start.
/// `Machine::new` would otherwise call `std::process::exit(1)` and take
/// the whole GUI down with it.
struct MissingDiskModal {
    missing: Vec<MissingDisk>,
}

impl App {
    fn new(mut prefs: GuiSettings) -> Self {
        // Resolution order on startup:
        //   1. prefs.active_machine present + in prefs.machines → load it.
        //   2. legacy prefs.last_config TOML still on disk → migrate it as
        //      a new named machine and adopt it.
        //   3. otherwise: open the New Machine dialog.
        let mut cfg = MachineConfig::default();
        let mut cfg_path: Option<PathBuf> = None;
        let mut opened_new_machine = false;
        let mut new_machine = NewMachineDialog::default();

        if let Some(name) = prefs.active_machine.clone() {
            if let Some(stored) = prefs.machines.get(&name).cloned() {
                cfg = stored;
            } else {
                // Stale pointer — fall through to migrate / dialog.
                prefs.active_machine = None;
            }
        }
        if prefs.active_machine.is_none() {
            if let Some(p) = prefs.last_config.clone() {
                if p.exists() {
                    cfg = MachineConfig::load_toml(&p.to_string_lossy());
                    cfg_path = Some(p.clone());
                    let stem = p.file_stem().and_then(|s| s.to_str()).unwrap_or("imported");
                    let name = prefs.unique_name(stem);
                    prefs.machines.insert(name.clone(), cfg.clone());
                    prefs.active_machine = Some(name);
                    // Clear the legacy pointer so we don't re-migrate next run.
                    prefs.last_config = None;
                    let _ = prefs.save();
                }
            }
        }
        if prefs.active_machine.is_none() {
            new_machine.open();
            opened_new_machine = true;
        }
        let _ = opened_new_machine; // (kept for future telemetry)

        Self {
            fullscreen: prefs.fullscreen,
            prefs,
            cfg,
            cfg_path,
            cfg_dirty: false,
            cfg_dirty_since: None,
            jit: JitEnv::default(),
            tab: Tab::General,
            emu: EmulatorHandle::spawn(),
            toast: None,
            stop_modal: None,
            missing_modal: None,
            new_machine,
            create_disk: CreateDiskDialog::default(),
            show_config_editor: false,
            save_state_name: "snap1".into(),
            restore_state_name: "snap1".into(),
            fb_tex: None,
            last_fb_seq: 0,
            input_state: input::InputState::default(),
        }
    }

    fn toast(&mut self, msg: impl Into<String>) {
        self.toast = Some((msg.into(), std::time::Instant::now()));
    }

    /// Mark the in-memory config as edited and arm the auto-save debounce.
    fn mark_dirty(&mut self) {
        self.cfg_dirty = true;
        self.cfg_dirty_since = Some(std::time::Instant::now());
    }

    /// Persist the current machine to disk and clear the dirty flag.
    fn flush_machine(&mut self) {
        if let Some(name) = self.prefs.active_machine.clone() {
            self.prefs.machines.insert(name, self.cfg.clone());
            if let Err(e) = self.prefs.save() {
                self.toast(format!("autosave failed: {e}"));
                return;
            }
        }
        self.cfg_dirty = false;
        self.cfg_dirty_since = None;
    }

    /// Debounced auto-save: flush ~600 ms after the most recent edit.
    fn maybe_autosave(&mut self) {
        if let Some(t) = self.cfg_dirty_since {
            if t.elapsed().as_millis() >= 600 { self.flush_machine(); }
        }
    }

    /// Switch the active machine in-memory and on disk.
    fn switch_to(&mut self, name: &str) {
        // Flush whatever we were holding first.
        if self.cfg_dirty { self.flush_machine(); }
        if let Some(cfg) = self.prefs.machines.get(name).cloned() {
            self.cfg = cfg;
            self.cfg_path = None;
            self.prefs.active_machine = Some(name.to_string());
            let _ = self.prefs.save();
            self.toast(format!("loaded '{name}'"));
        }
    }

    fn save_config(&mut self, path: PathBuf) {
        match cfg_to_toml(&self.cfg) {
            Ok(s) => match std::fs::write(&path, s) {
                Ok(_) => {
                    self.prefs.push_recent(path.clone());
                    self.cfg_path = Some(path);
                    self.cfg_dirty = false;
                    self.toast("config saved");
                }
                Err(e) => self.toast(format!("save failed: {e}")),
            },
            Err(e) => self.toast(format!("serialize failed: {e}")),
        }
    }

    fn start_emulator(&mut self) {
        // Flush any pending edits before the machine starts so the on-disk
        // copy matches what we're about to boot.
        if self.cfg_dirty { self.flush_machine(); }
        if iris::build_features::LIGHTNING && self.cfg.gdb_port.is_some() {
            // GDB stub is a no-op under lightning; silently drop the setting
            // so we don't hand the executor a port it can't honour.
            self.cfg.gdb_port = None;
        }
        if let Err(e) = self.cfg.validate() {
            self.toast(format!("invalid config: {e}"));
            return;
        }
        // Preflight: Machine::new will call std::process::exit(1) on the
        // first SCSI device whose backing file is missing — we'd lose the
        // GUI process. Catch that case here and prompt the user instead.
        let missing = self.missing_disks();
        if !missing.is_empty() {
            self.missing_modal = Some(MissingDiskModal { missing });
            return;
        }
        // Surface the embedded-PROM fallback so it's clear the start did
        // happen (iris::prom::Prom::from_file_or_embedded handles this
        // transparently — we just echo it to the toast).
        if !std::path::Path::new(&self.cfg.prom).exists() {
            self.toast(format!("'{}' not found — using embedded PROM", self.cfg.prom));
        }
        self.jit.export();
        self.emu.send(Cmd::Start(Box::new(self.cfg.clone())));
    }

    /// Walk the configured SCSI devices and report any whose image file
    /// is missing. Scratch volumes are skipped (iris auto-creates those).
    /// For CD-ROMs the device is "present" if either the primary path or
    /// any disc in the changer list exists.
    fn missing_disks(&self) -> Vec<MissingDisk> {
        let mut out = Vec::new();
        for (&id, dev) in &self.cfg.scsi {
            if dev.scratch { continue; }
            // Empty CD-ROM (no path, no changer entries) means "drive present,
            // tray empty" — a valid configured state, not missing.
            if dev.cdrom && dev.path.is_empty() && dev.discs.is_empty() {
                continue;
            }
            let primary_ok = !dev.path.is_empty() && std::path::Path::new(&dev.path).exists();
            let any_disc_ok = dev.discs.iter().any(|d| std::path::Path::new(d).exists());
            let present = primary_ok || (dev.cdrom && any_disc_ok);
            if !present {
                out.push(MissingDisk { id, path: dev.path.clone(), cdrom: dev.cdrom });
            }
        }
        out.sort_by_key(|m| m.id);
        out
    }

    /// Detach the given SCSI IDs from the live config and (optionally) try Start again.
    fn detach_and_start(&mut self, ids: &[u8]) {
        for id in ids { self.cfg.scsi.remove(id); }
        self.mark_dirty();
        self.start_emulator();
    }

    fn request_stop(&mut self) {
        let reasons = evaluate(&self.emu.status, &self.cfg);
        if reasons.is_empty() {
            self.emu.send(Cmd::Stop);
        } else {
            self.stop_modal = Some(StopModal { lines: reason_lines(&reasons) });
        }
    }

    fn handle_events(&mut self, ctx: &egui::Context) {
        for evt in self.emu.drain_events() {
            match evt {
                Evt::Started   => self.toast("emulator started"),
                Evt::Stopped   => self.toast("emulator stopped"),
                Evt::PowerOff  => self.toast("guest powered off (safe to stop)"),
                Evt::StateSaved(n)    => self.toast(format!("state saved: {n}")),
                Evt::StateRestored(n) => self.toast(format!("state restored: {n}")),
                Evt::Screenshot(p)    => self.toast(format!("screenshot: {}", p.display())),
                Evt::Error(e)         => self.toast(format!("error: {e}")),
                Evt::Status(_) => {}
            }
        }
        // Repaint cadence: ~60 fps while the emulator is running so we
        // can pull the latest framebuffer; lazy otherwise to save CPU.
        let next = if self.emu.is_running() { 16 } else { 250 };
        ctx.request_repaint_after(std::time::Duration::from_millis(next));
    }

    fn menu_bar(&mut self, ui: &mut egui::Ui, ctx: &egui::Context) {
        egui::menu::bar(ui, |ui| {
            ui.menu_button("File", |ui| {
                ui.set_min_width(220.0);
                if ui.button("New machine…").clicked() {
                    self.new_machine.open();
                    ui.close_menu();
                }
                ui.menu_button("Switch to machine", |ui| {
                    ui.set_min_width(200.0);
                    let active = self.prefs.active_machine.clone();
                    let names: Vec<String> = self.prefs.machines.keys().cloned().collect();
                    if names.is_empty() {
                        ui.label(RichText::new("(no saved machines yet)").weak());
                    }
                    let mut want_switch: Option<String> = None;
                    for name in names {
                        let marker = if active.as_deref() == Some(&name) { "● " } else { "  " };
                        if ui.button(format!("{marker}{name}")).clicked() {
                            want_switch = Some(name);
                            ui.close_menu();
                        }
                    }
                    if let Some(n) = want_switch { self.switch_to(&n); }
                });
                ui.menu_button("Rename current…", |ui| {
                    let cur = self.prefs.active_machine.clone();
                    if let Some(name) = cur {
                        ui.label(format!("Current: {name}"));
                        let mut new_name = name.clone();
                        ui.text_edit_singleline(&mut new_name);
                        if ui.button("Rename").clicked() && !new_name.trim().is_empty() && new_name != name {
                            let n = self.prefs.unique_name(new_name.trim());
                            if let Some(cfg) = self.prefs.machines.remove(&name) {
                                self.prefs.machines.insert(n.clone(), cfg);
                                self.prefs.active_machine = Some(n.clone());
                                let _ = self.prefs.save();
                                self.toast(format!("renamed → '{n}'"));
                            }
                            ui.close_menu();
                        }
                    } else {
                        ui.label(RichText::new("(no active machine)").weak());
                    }
                });
                let active = self.prefs.active_machine.clone();
                if ui.add_enabled(active.is_some(), egui::Button::new("Delete current machine")).clicked() {
                    if let Some(name) = active {
                        self.prefs.machines.remove(&name);
                        self.prefs.active_machine = self.prefs.machines.keys().next().cloned();
                        if let Some(next) = self.prefs.active_machine.clone() {
                            self.cfg = self.prefs.machines[&next].clone();
                        } else {
                            self.cfg = MachineConfig::default();
                            self.new_machine.open();
                        }
                        let _ = self.prefs.save();
                        self.toast(format!("deleted '{name}'"));
                    }
                    ui.close_menu();
                }
                ui.separator();
                if ui.button("Import iris.toml…").clicked() {
                    if let Some(path) = native_open_dialog("Import iris.toml", &[("TOML", &["toml"])]) {
                        let cfg = MachineConfig::load_toml(&path.to_string_lossy());
                        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("imported");
                        let name = self.prefs.unique_name(stem);
                        self.prefs.machines.insert(name.clone(), cfg.clone());
                        self.prefs.active_machine = Some(name.clone());
                        self.cfg = cfg;
                        self.cfg_path = Some(path);
                        self.flush_machine();
                        self.toast(format!("imported as '{name}'"));
                    }
                    ui.close_menu();
                }
                if ui.button("Export current to iris.toml…").clicked() {
                    if let Some(path) = native_save_dialog("Export iris.toml", &[("TOML", &["toml"])]) {
                        self.save_config(path);
                    }
                    ui.close_menu();
                }
                ui.separator();
                if ui.button("Quit").clicked() {
                    if self.cfg_dirty { self.flush_machine(); }
                    ctx.send_viewport_cmd(ViewportCommand::Close);
                }
            });
            ui.menu_button("Machine", |ui| {
                let running = self.emu.is_running();
                if ui.add_enabled(!running, egui::Button::new("Start")).clicked() {
                    self.start_emulator();
                    ui.close_menu();
                }
                if ui.add_enabled(running, egui::Button::new("Stop")).clicked() {
                    self.request_stop();
                    ui.close_menu();
                }
                if ui.add_enabled(running, egui::Button::new("Reset")).clicked() {
                    self.emu.send(Cmd::Stop);
                    self.start_emulator();
                    ui.close_menu();
                }
                ui.separator();
                ui.horizontal(|ui| {
                    ui.label("Save state:");
                    ui.add(egui::TextEdit::singleline(&mut self.save_state_name).desired_width(120.0));
                    if ui.button("Save").clicked() {
                        self.emu.send(Cmd::SaveState(self.save_state_name.clone()));
                    }
                });
                ui.horizontal(|ui| {
                    ui.label("Restore state:");
                    ui.add(egui::TextEdit::singleline(&mut self.restore_state_name).desired_width(120.0));
                    if ui.button("Restore").clicked() {
                        self.emu.send(Cmd::RestoreState(self.restore_state_name.clone()));
                    }
                });
                ui.separator();
                if ui.button("Screenshot…").clicked() {
                    if let Some(p) = native_save_dialog("Save screenshot", &[("PNG", &["png"])]) {
                        self.emu.send(Cmd::Screenshot(p));
                    }
                    ui.close_menu();
                }
            });
            ui.menu_button("Memory", |ui| {
                ui.set_min_width(220.0);
                let total: u32 = self.cfg.banks.iter().sum();
                ui.label(RichText::new(format!("Total: {total} MB")).strong());
                ui.separator();
                ui.label("Quick presets (auto-distributed):");
                for &p in &[32u32, 64, 96, 128, 192, 256] {
                    if ui.button(format!("{p} MB")).clicked() {
                        self.cfg.banks = distribute_ram(p);
                        self.mark_dirty();
                        self.toast(format!("RAM set to {p} MB ({:?})", self.cfg.banks));
                        ui.close_menu();
                    }
                }
                ui.separator();
                ui.label("Per-bank (advanced):");
                for i in 0..4 {
                    ui.menu_button(format!("Bank {i}: {} MB", self.cfg.banks[i]), |ui| {
                        for &sz in iris::config::VALID_BANK_SIZES {
                            if ui.button(format!("{sz} MB")).clicked() {
                                self.cfg.banks[i] = sz;
                                self.mark_dirty();
                                ui.close_menu();
                            }
                        }
                    });
                }
            });
            ui.menu_button("SCSI", |ui| {
                let action = scsi_menu::draw(ui, &self.cfg);
                match action {
                    scsi_menu::ScsiAction::None => {}
                    scsi_menu::ScsiAction::CreateBlank { id } => {
                        self.create_disk.open_for(id);
                    }
                    other => {
                        if let Some(msg) = scsi_menu::apply(&mut self.cfg, other) {
                            self.mark_dirty();
                            self.toast(msg);
                        }
                    }
                }
            });
            ui.menu_button("View", |ui| {
                if ui.button(if self.fullscreen { "Exit fullscreen (F11)" } else { "Fullscreen (F11)" }).clicked() {
                    self.fullscreen = !self.fullscreen;
                    ctx.send_viewport_cmd(ViewportCommand::Fullscreen(self.fullscreen));
                    ui.close_menu();
                }
                ui.horizontal(|ui| {
                    ui.label("UI scale");
                    // Adjust the slider freely; only commit to the live zoom
                    // factor on Apply. Applying mid-drag rescales the whole UI
                    // (slider included) under the cursor, which makes the value
                    // jump around — hence the explicit button.
                    ui.add(egui::Slider::new(&mut self.prefs.ui_scale, UI_SCALE_MIN..=UI_SCALE_MAX));
                    if ui.button("Apply").clicked() {
                        ctx.set_zoom_factor(self.prefs.ui_scale);
                    }
                });
                ui.label(RichText::new("Ctrl+= / Ctrl+- / Ctrl+0 to zoom").weak().small());
            });
            ui.menu_button("Help", |ui| {
                ui.label("iris-gui — SGI Indy emulator launcher");
                ui.label(format!("iris-gui {}", env!("CARGO_PKG_VERSION")));
                ui.separator();
                ui.label(RichText::new("Build features:").strong());
                use iris::build_features as bf;
                ui.label(format!("  chd:       {}", if bf::CHD { "on" } else { "off" }));
                ui.label(format!("  camera:    {}", if bf::CAMERA { "on" } else { "off" }));
                ui.label(format!("  jit:       {}", if bf::JIT { "on" } else { "off" }));
                ui.label(format!("  rex-jit:   {}", if bf::REX_JIT { "on" } else { "off" }));
                ui.label(format!("  lightning: {}", if bf::LIGHTNING { "on (no debug)" } else { "off" }));
                ui.hyperlink_to("README", "https://github.com/dsarfati/iris");
            });
        });
    }

    fn toolbar(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            let running = self.emu.is_running();
            if !running {
                if ui.add(egui::Button::new(RichText::new("▶ Start").size(16.0))
                    .fill(Color32::from_rgb(40, 110, 40))).clicked()
                {
                    self.start_emulator();
                }
            } else if ui.add(egui::Button::new(RichText::new("■ Stop").size(16.0))
                .fill(Color32::from_rgb(160, 60, 60))).clicked()
            {
                self.request_stop();
            }
            ui.separator();
            if ui.add_enabled(running, egui::Button::new("💾 Save state")).clicked() {
                self.emu.send(Cmd::SaveState(self.save_state_name.clone()));
            }
            if ui.add_enabled(running, egui::Button::new("↶ Restore state")).clicked() {
                self.emu.send(Cmd::RestoreState(self.restore_state_name.clone()));
            }
            ui.separator();
            let edit_label = if self.show_config_editor { "Hide config editor" } else { "Edit config…" };
            if ui.button(edit_label).clicked() {
                self.show_config_editor = !self.show_config_editor;
            }
            if self.show_config_editor {
                if ui.button("Network").clicked()  { self.tab = Tab::Network; }
                if ui.button("Video-In").clicked() { self.tab = Tab::VideoIn; }
                if ui.button("Debug").clicked()    { self.tab = Tab::Debug; }
                if ui.button("CI").clicked()       { self.tab = Tab::Ci; }
            }

            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                let status = if self.emu.status.power_off_seen {
                    RichText::new("halted").color(Color32::LIGHT_GRAY)
                } else if self.emu.status.in_prom {
                    RichText::new("PROM").color(Color32::LIGHT_BLUE)
                } else if running {
                    RichText::new("IRIX running").color(Color32::LIGHT_GREEN)
                } else {
                    RichText::new("stopped").color(Color32::GRAY)
                };
                ui.label(status);
                if running {
                    ui.label(format!("{:.0} MIPS", self.emu.status.mips));
                }
            });
        });
    }

    /// Draw the live REX3 framebuffer as an egui image, scaled to fit
    /// the available area while preserving aspect ratio.
    fn framebuffer_panel(&mut self, ui: &mut egui::Ui) {
        // Lock-free check first: only clone + re-upload the (multi-MB)
        // framebuffer when REX3 has actually produced a new frame. Cloning on
        // every 60 fps repaint regardless was ~300 MB/s of pointless copying
        // and needless lock contention with the REX3 refresh thread.
        let seq = self.emu.frame_sink.seq();
        if seq == 0 {
            ui.centered_and_justified(|ui| {
                ui.label(RichText::new("Emulator running — waiting for first REX3 frame…")
                    .color(Color32::LIGHT_GRAY));
            });
            return;
        }

        if self.fb_tex.is_none() || seq != self.last_fb_seq {
            let frame = self.emu.frame_sink.snapshot();
            if frame.width == 0 || frame.height == 0 { return; }
            let img = egui::ColorImage::from_rgba_unmultiplied(
                [frame.width, frame.height], &frame.rgba);
            match &mut self.fb_tex {
                Some(t) => t.set(img, egui::TextureOptions::NEAREST),
                None => {
                    self.fb_tex = Some(ui.ctx().load_texture(
                        "rex3_fb", img, egui::TextureOptions::NEAREST));
                }
            }
            self.last_fb_seq = frame.seq;
        }

        let mut fb_rect = egui::Rect::NOTHING;
        if let Some(tex) = &self.fb_tex {
            let avail = ui.available_size();
            let tex_size = tex.size_vec2();
            let fb_aspect = tex_size.x / tex_size.y;
            let avail_aspect = avail.x / avail.y;
            let size = if avail_aspect > fb_aspect {
                egui::vec2(avail.y * fb_aspect, avail.y)
            } else {
                egui::vec2(avail.x, avail.x / fb_aspect)
            };
            ui.centered_and_justified(|ui| {
                let response = ui.add(
                    egui::Image::new((tex.id(), size)).fit_to_exact_size(size).sense(egui::Sense::click())
                );
                fb_rect = response.rect;
                // Take keyboard focus so that egui delivers Key events
                // to us instead of routing them to other widgets when
                // the user clicks into the FB.
                if response.clicked() { response.request_focus(); }
            });
        }

        // Pump egui input → PS/2 controller. Mouse/keyboard only reach the
        // guest while captured (click the framebuffer to capture, Ctrl+Alt+Esc
        // to release), so menu clicks and config typing don't leak in.
        let ps2 = self.emu.ps2.lock().clone();
        if let Some(ps2) = ps2 {
            input::pump(ui.ctx(), fb_rect, &ps2, &mut self.input_state, self.cfg.mouse_scroll_pixels_per_line);
        }

        // Capture hint, drawn over the framebuffer.
        if fb_rect.is_positive() {
            let hint = if self.input_state.captured {
                "Ctrl+Alt+Esc to release mouse"
            } else {
                "Click to capture mouse / keyboard"
            };
            ui.painter().text(
                fb_rect.center_bottom() + egui::vec2(0.0, -6.0),
                egui::Align2::CENTER_BOTTOM,
                hint,
                egui::FontId::proportional(12.0),
                Color32::from_white_alpha(140),
            );
        }
    }

    fn central_tabs(&mut self, ui: &mut egui::Ui) {
        ui.horizontal_wrapped(|ui| {
            for &t in Tab::ALL {
                ui.selectable_value(&mut self.tab, t, t.label());
            }
        });
        ui.separator();
        show_tab(ui, self.tab, &mut self.cfg, &mut self.jit);
    }

    fn welcome_panel(&mut self, ui: &mut egui::Ui) {
        ui.add_space(8.0);
        ui.heading("iris — SGI Indy emulator");
        ui.add_space(4.0);

        let name = self.prefs.active_machine.as_deref().unwrap_or("(unsaved)");
        ui.label(format!("Machine: {name}"));
        if self.cfg_dirty {
            ui.label(RichText::new("(autosave pending…)").weak().small());
        }
        ui.add_space(8.0);

        let total_ram: u32 = self.cfg.banks.iter().sum();
        ui.label(RichText::new("Machine summary").strong());
        egui::Grid::new("summary_grid").num_columns(2).striped(true).show(ui, |ui| {
            ui.label("PROM");
            ui.label(if std::path::Path::new(&self.cfg.prom).exists() {
                self.cfg.prom.clone()
            } else {
                format!("{} (missing → embedded fallback)", self.cfg.prom)
            });
            ui.end_row();
            ui.label("NVRAM");
            ui.label(&self.cfg.nvram);
            ui.end_row();
            ui.label("RAM");
            ui.label(format!("{total_ram} MB ({:?})", self.cfg.banks));
            ui.end_row();
            ui.label("Drives");
            ui.vertical(|ui| {
                let mut ids: Vec<u8> = self.cfg.scsi.keys().copied().collect();
                ids.sort();
                if ids.is_empty() {
                    ui.label(RichText::new("(none)").weak());
                }
                for id in ids {
                    let d = &self.cfg.scsi[&id];
                    let kind = if d.cdrom { "CD" } else { "HDD" };
                    ui.label(format!("scsi{id} {kind}: {}", d.path));
                }
                ui.label(RichText::new("Use the SCSI menu to attach / detach / replace.").weak().small());
            });
            ui.end_row();
            ui.label("Network");
            ui.label(self.cfg.nat_subnet.clone().unwrap_or_else(|| "192.168.0.0/24 (default)".into()));
            ui.end_row();
        });

        ui.add_space(12.0);
        // Welcome panel is only rendered when the emulator is stopped
        // (the central panel switches to the framebuffer when running),
        // so a single Start button is sufficient here.
        if ui.add(egui::Button::new(RichText::new("▶ Start emulator").size(20.0))
            .fill(Color32::from_rgb(40, 120, 40))
            .min_size(egui::vec2(220.0, 44.0))).clicked()
        {
            self.start_emulator();
        }
    }

    fn status_bar(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            let name = self.prefs.active_machine.as_deref().unwrap_or("(unsaved)");
            ui.label(format!("Machine: {name}{}", if self.cfg_dirty { " *" } else { "" }));
            ui.separator();
            ui.label(format!("Dirty COW: {}", self.emu.status.dirty_cow));
            if let Some((msg, when)) = self.toast.clone() {
                if when.elapsed().as_secs() < 5 {
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        ui.label(RichText::new(msg).color(Color32::YELLOW));
                    });
                } else {
                    self.toast = None;
                }
            }
        });
    }
}

impl eframe::App for App {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        self.handle_events(ctx);
        self.maybe_autosave();

        // F11 toggles fullscreen.
        if ctx.input(|i| i.key_pressed(egui::Key::F11)) {
            self.fullscreen = !self.fullscreen;
            ctx.send_viewport_cmd(ViewportCommand::Fullscreen(self.fullscreen));
        }

        // Ctrl + / Ctrl - / Ctrl 0 zoom controls (helps on Linux where egui's
        // default text size can look small on HiDPI / fractional-scale Wayland).
        let (zoom_in, zoom_out, zoom_reset) = ctx.input(|i| (
            i.modifiers.command && (i.key_pressed(egui::Key::Plus) || i.key_pressed(egui::Key::Equals)),
            i.modifiers.command && i.key_pressed(egui::Key::Minus),
            i.modifiers.command && i.key_pressed(egui::Key::Num0),
        ));
        if zoom_in    { self.prefs.ui_scale = (self.prefs.ui_scale + 0.1).min(UI_SCALE_MAX); ctx.set_zoom_factor(self.prefs.ui_scale); }
        if zoom_out   { self.prefs.ui_scale = (self.prefs.ui_scale - 0.1).max(UI_SCALE_MIN); ctx.set_zoom_factor(self.prefs.ui_scale); }
        if zoom_reset { self.prefs.ui_scale = settings::UI_SCALE_DEFAULT; ctx.set_zoom_factor(self.prefs.ui_scale); }

        // In fullscreen, only reveal menu/toolbar when the cursor is near the top.
        let pointer_y = ctx.input(|i| i.pointer.latest_pos().map(|p| p.y).unwrap_or(f32::MAX));
        let chrome_visible = !self.fullscreen || pointer_y < 36.0;

        if chrome_visible {
            egui::TopBottomPanel::top("menu_bar").show(ctx, |ui| self.menu_bar(ui, ctx));
            egui::TopBottomPanel::top("toolbar").show(ctx, |ui| self.toolbar(ui));
        }
        if !self.fullscreen {
            egui::TopBottomPanel::bottom("status_bar").show(ctx, |ui| self.status_bar(ui));
        }

        // Config editor lives in a collapsible side panel so the emulator
        // screen (central panel) is never hidden by it. The toolbar's
        // "Edit config… / Hide config editor" toggle drives the collapse;
        // `show_animated` slides it in/out.
        egui::SidePanel::right("config_editor")
            .resizable(true)
            .default_width(420.0)
            .show_animated(ctx, self.show_config_editor, |ui| {
                ui.horizontal(|ui| {
                    ui.heading("Configuration");
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if ui.button("×").on_hover_text("Hide config editor").clicked() {
                            self.show_config_editor = false;
                        }
                    });
                });
                ui.separator();
                egui::ScrollArea::vertical().show(ui, |ui| self.central_tabs(ui));
            });

        egui::CentralPanel::default().show(ctx, |ui| {
            // The central panel always shows the emulator screen when the
            // machine is running (the REX3 framebuffer), falling back to the
            // welcome / status summary when idle. The config editor no longer
            // takes this space — it's the side panel above.
            if self.emu.is_running() {
                self.framebuffer_panel(ui);
            } else {
                // Emulator not running: make sure a leftover mouse capture is
                // released so the host cursor isn't stuck hidden/locked.
                input::force_release(ui.ctx(), &mut self.input_state);
                self.welcome_panel(ui);
            }
        });

        // New machine dialog.
        self.new_machine.show(ctx);
        if let Some(result) = self.new_machine.take_result() {
            let name = self.prefs.unique_name(&result.name);
            self.prefs.machines.insert(name.clone(), result.cfg.clone());
            self.prefs.active_machine = Some(name.clone());
            self.cfg = result.cfg;
            self.cfg_path = None;
            self.flush_machine();
            self.toast(format!("created machine '{name}'"));
        }

        // Create blank disk dialog.
        self.create_disk.show(ctx);
        if let Some(result) = self.create_disk.take_result() {
            let path_str = result.path.to_string_lossy().into_owned();
            self.cfg.scsi.insert(result.scsi_id, iris::config::ScsiDeviceConfig {
                path: path_str.clone(), discs: vec![], cdrom: false,
                overlay: false, scratch: false, size_mb: None,
            });
            self.mark_dirty();
            self.toast(format!("created {path_str} and attached at scsi{}", result.scsi_id));
        }

        // Safe-stop confirmation modal.
        let mut close_modal = false;
        let mut do_force = false;
        let mut do_halt  = false;
        if let Some(modal) = &self.stop_modal {
            egui::Window::new("Confirm stop")
                .collapsible(false)
                .resizable(false)
                .anchor(egui::Align2::CENTER_CENTER, [0.0, 0.0])
                .show(ctx, |ui| {
                    ui.label(RichText::new("Stopping now may corrupt the disk image:").strong());
                    for line in &modal.lines { ui.label(format!("• {line}")); }
                    ui.add_space(8.0);
                    ui.horizontal(|ui| {
                        if ui.button("Cancel").clicked() { close_modal = true; }
                        if ui.button("Send IRIX halt").clicked() { do_halt = true; close_modal = true; }
                        if ui.add(egui::Button::new(RichText::new("Force stop").color(Color32::WHITE))
                            .fill(Color32::from_rgb(140, 40, 40))).clicked()
                        {
                            do_force = true; close_modal = true;
                        }
                    });
                });
        }
        if close_modal { self.stop_modal = None; }
        if do_force { self.emu.send(Cmd::Stop); }
        if do_halt  {
            // iris always opens 127.0.0.1:8881 as the ttyd1 (IRIX serial
            // console) TCP listener in non-CI mode. Connect to it,
            // write "halt\n", disconnect. IRIX takes a few seconds to
            // shut down cleanly; the user can hit Stop again once the
            // PROM "halted" message appears.
            use std::io::Write as _;
            match std::net::TcpStream::connect_timeout(
                &"127.0.0.1:8881".parse().unwrap(),
                std::time::Duration::from_millis(500),
            ) {
                Ok(mut s) => {
                    let _ = s.write_all(b"halt\n");
                    self.toast("sent 'halt' to IRIX — wait for shutdown, then Stop");
                }
                Err(e) => {
                    self.toast(format!("halt failed: {e} — falling back to Force stop"));
                    self.emu.send(Cmd::Stop);
                }
            }
        }

        // Missing-disk modal.
        enum MissingChoice { None, Cancel, Detach, EditDisks }
        let mut choice = MissingChoice::None;
        if let Some(modal) = &self.missing_modal {
            egui::Window::new("Missing disk image(s)")
                .collapsible(false)
                .resizable(false)
                .anchor(egui::Align2::CENTER_CENTER, [0.0, 0.0])
                .show(ctx, |ui| {
                    ui.label(RichText::new("The following SCSI image files are missing:").strong());
                    for m in &modal.missing {
                        let kind = if m.cdrom { "CD-ROM" } else { "HDD" };
                        ui.label(format!("• scsi{} ({kind}): {}", m.id, m.path));
                    }
                    ui.add_space(8.0);
                    ui.label(RichText::new(
                        "iris would terminate the process if started in this state. \
                         Choose how to proceed:").weak());
                    ui.add_space(4.0);
                    ui.horizontal(|ui| {
                        if ui.button("Cancel").clicked() { choice = MissingChoice::Cancel; }
                        if ui.button("Edit Disks tab").clicked() { choice = MissingChoice::EditDisks; }
                        if ui.add(egui::Button::new("Detach missing & start")
                            .fill(Color32::from_rgb(60, 90, 140))).clicked()
                        {
                            choice = MissingChoice::Detach;
                        }
                    });
                });
        }
        match choice {
            MissingChoice::None => {}
            MissingChoice::Cancel => { self.missing_modal = None; }
            MissingChoice::EditDisks => {
                // Switching the tab alone is invisible if the config editor
                // side panel is collapsed (its default state) — open it too,
                // or the button appears to do nothing.
                self.tab = config_ui::Tab::Disks;
                self.show_config_editor = true;
                self.missing_modal = None;
            }
            MissingChoice::Detach => {
                let ids: Vec<u8> = self.missing_modal.as_ref()
                    .map(|m| m.missing.iter().map(|d| d.id).collect())
                    .unwrap_or_default();
                self.missing_modal = None;
                self.detach_and_start(&ids);
            }
        }
    }

    fn on_exit(&mut self, _gl: Option<&eframe::glow::Context>) {
        self.prefs.fullscreen = self.fullscreen;
        // Make sure the latest cfg lands in `machines` before save().
        if self.cfg_dirty { self.flush_machine(); } else { let _ = self.prefs.save(); }
        // Synchronously stop the machine and join the worker, so a running
        // guest is cleaned up even if the user closed the window without
        // pressing Stop (rather than relying on Drop ordering / racing
        // process teardown). Bounded by the worker's stop timeout.
        self.emu.shutdown();
        // Release the single-instance lock so the next launch sees a clean
        // start (a crash that skips this just leaves a stale, harmless pidfile).
        single_instance::release();
    }
}

// --- platform dialogs ------------------------------------------------------
//
// We avoid `rfd` as a dependency for now to keep the dep tree slim. Use
// `zenity` / `osascript` if available; otherwise return None and let the
// caller paste a path into the recent-files / save-state fields.
fn native_open_dialog(title: &str, filters: &[(&str, &[&str])]) -> Option<PathBuf> {
    let mut d = rfd::FileDialog::new().set_title(title);
    for (name, exts) in filters { d = d.add_filter(*name, exts); }
    d.pick_file()
}
fn native_save_dialog(title: &str, filters: &[(&str, &[&str])]) -> Option<PathBuf> {
    let mut d = rfd::FileDialog::new().set_title(title);
    for (name, exts) in filters { d = d.add_filter(*name, exts); }
    d.save_file()
}
